name: virtual-earth
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - scikit-learn
  - networkx
  - tqdm
  - opencv
  - pillow
  - jupyter
  - notebook
  - tensorboard
  - pip
  - pip:
    - wandb>=0.12.0
    - hydra-core>=1.1.0
    - omegaconf>=2.1.0
    - gymnasium>=0.26.0
    - stable-baselines3>=1.6.0
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - websockets>=10.0
    - pytest>=6.2.0
    - pytest-cov>=2.12.0
    - black>=21.0.0
    - flake8>=3.9.0
    - mypy>=0.910
