# Interpretability-First Configuration

defaults:
  - _self_
  - /population: structured_learning
  - /ontology: slot_grammar

environment:
  type: "interpretable_referential"
  dual_channel: true  # Enable C-Channel + E-Channel
  slot_structure: true
  attributes:
    action: 8      # Actions (move, take, etc.)
    object: 12     # Object types  
    attribute: 16  # Colors, shapes, sizes
    location: 24   # Spatial positions
    modifier: 6    # Quantifiers, negations
  
grammar:
  slot_order: ["action", "object", "attribute", "location", "modifier"]
  min_hamming_distance: 3  # Anti-confusion constraint
  anchor_words: 12         # Fixed vocabulary core
  morphology_rules: 20     # Productive word formation

communication:
  vocab_size: 256
  max_message_length: 12
  slot_tokens: true        # Position-semantic alignment
  explanation_channel: true # E-Channel enabled
  noise_robustness: 0.05   # 5% character corruption tolerance

objectives:
  # Standard terms
  alpha: 1.0      # Task success
  beta: 0.6       # Mutual information  
  gamma: 0.4      # Topological similarity
  lambda1: 0.15   # Length penalty
  lambda2: 0.08   # Entropy penalty
  
  # Interpretability terms  
  delta1: 0.5     # C↔E consistency
  delta2: 0.3     # Slot alignment (CTC)
  delta3: 0.4     # Few-shot learnability
  
  # Anti-encryption
  public_listener_weight: 0.2
  noise_robustness_weight: 0.1
  minimal_edit_weight: 0.15

training:
  algorithm: "ppo"
  total_steps: 2000000
  teaching_protocol: true
  repair_rewards: true
  cross_population_bridge: true
  
evaluation:
  interpretability_tests: true
  teaching_evaluation: true
  few_shot_learning: true
  cross_dialect_translation: true
  compositional_generalization: true
